#!/bin/env sh

if [ -z "$1" ] || [ -z "$2" ]; then
    exit 1
fi

eval $1
value=$(printf "%.0f" $(eval $2))
p=$((value/10))
np=$((10 - p))
tp=$(printf "%${p}s" | tr " " "=")
tnp=$(printf "%${np}s")
printf '|%s%s|%3s%%' "$tp" "$tnp" "$value" | aosd_cat -n "DejaVu Sans Mono 60" -u 500 -p 2 -y 50 -x -10  -f 0 -o 0 -t 0
